CREATE ALIAS IF NOT EXISTS getDate AS
    'java.util.Date getDate() { return new java.util.Date(); }';

CREATE TABLE IF NOT EXISTS users
    (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT,
        email TEXT NOT NULL,
        login TEXT NOT NULL,
        birthday DATE

        CONSTRAINT email
            CHECK (email LIKE '%@%'),
        CONSTRAINT login_c
            CHECK (login NOT LIKE '' AND login NOT LIKE '% %'),
        CONSTRAINT birthday_c
            CHECK (CAST(birthday AS date ) <= CAST(getDate() AS date))
);

CREATE TABLE IF NOT EXISTS mpa
    (
    id BIGINT PRIMARY KEY,
    name TEXT NOT NULL
    );

  CREATE TABLE IF NOT EXISTS films
    (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        description TEXT,
        releaseDate TEXT,
        duration LONG,
        rate BIGINT,
        mpa BIGINT REFERENCES mpa (id)
    );

CREATE TABLE IF NOT EXISTS likes
    (
        film_id BIGINT NOT NULL REFERENCES films (id),
        user_id BIGINT NOT NULL REFERENCES users (id)
    );

CREATE TABLE IF NOT EXISTS friendship
    (
    user_id BIGINT NOT NULL REFERENCES users (id),
    friend_id BIGINT NOT NULL
    );



CREATE TABLE IF NOT EXISTS genres
    (
    id BIGINT PRIMARY KEY,
    name TEXT NOT NULL
    );

CREATE TABLE IF NOT EXISTS film_genre
    (
    film_id BIGINT NOT NULL REFERENCES films (id),
    genre_id BIGINT NOT NULL REFERENCES genres (id)
    );
